name: Good Talent test
favicon: null
layout_spectrum: 0.49522
typography_spectrum: 0.49571
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#a8a8a8'
    - '#616161'
    - '#f63645'
  brandStrength: 0.9375
  lightness: 0.675722268410027
  saturation: 0.3732596468180418
  rhythmicContrast: 0.7975726069416851
purpose: []
